### PR TITLE
fix: Missing symlink for 99-pipewire-default.conf

### PR DESCRIPTION
**Pull request by mmstick**
Required for the setting to have an affect.

Can test by playing a wav audio file with `aplay` and checking that the output appears in EasyEffects.

Should check that Davinci Resolve is not affected with audio delay.

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
Just wanted to confirm this does not seem to affect DaVinci Resolve audio (the file being symlinked is still set to `type pulse` instead of `type pipewire`, so this isn't interfering with that fix.) This does get `aplay` working when `pavucontrol` is running where it previously reported "Device or resource busy," makes `aplay` and Resolve able to play audio at the same time, and gets Resolve and `aplay` both showing up in EasyEffects where they did not before.

(I'll let @linuxgnuru finish his testing too.)

**Comment by linuxgnuru** [comment]
The symlink didn't fix the issue when tested on a kudu6 nor on a pang10 however on non-system76 machines the symlink did fix the issue. So if the following error is reported the symlink fix works:

```
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
aplay: main:831: audio open error: No such file or directory
```

On the kudu6 and pang10 I got a different error:
```
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so: cannot open shared object file: No such file or directory)
aplay: main:831: audio open error: No such device or address
```
which was fixed by installing the `libasound2-plugins` package.

**Comment by mmstick** [comment]
Sounds like we need to add that package to our desktop metapackage. Or perhaps here?

**Comment by linuxgnuru** [comment]
I don't have access to a davinci activation key so can't test that part but aplay of a wav file does work and is shown in EasyEffects

**Comment by jacobgkau** [comment]
> I don't have access to a davinci activation key so can't test that part but aplay of a wav file does work and is shown in EasyEffects

You don't need an activation key to use Resolve, the free (gratis) version plays back ProRes video with 16-bit PCM WAV audio (I think it also plays back AVI and some other intraframe-compressed or uncompressed codecs.) We have a [support article](https://support.system76.com/articles/install-davinci-resolve) explaining how to install Resolve, and for testing audio specifically, a WAV file exported from Audacity with default settings should work if you don't want to go through the trouble of converting a video to ProRes with ffmpeg. Like I said, Resolve's looking good with this PR.

**Comment by linuxgnuru** [comment]
> > I don't have access to a davinci activation key so can't test that part but aplay of a wav file does work and is shown in EasyEffects
> 
> You don't need an activation key to use Resolve, the free (gratis) version plays back ProRes video with 16-bit PCM WAV audio (I think it also plays back AVI and some other intraframe-compressed or uncompressed codecs.) We have a [support article](https://support.system76.com/articles/install-davinci-resolve) explaining how to install Resolve, and for testing audio specifically, a WAV file exported from Audacity with default settings should work if you don't want to go through the trouble of converting a video to ProRes with ffmpeg. Like I said, Resolve's looking good with this PR.

ah, I was using a deb for davinci that Aaron had made which was the studio version. I thought the issue was with davinci with a 1 second delay which is why I was testing it.

**Comment by jacobgkau** [comment]
> I thought the issue was with davinci with a 1 second delay which is why I was testing it.

That was already fixed with https://github.com/pop-os/pipewire/pull/2. It just needed regression testing with this PR since the file where the fix was made is the one now being symlinked.

**Review by linuxgnuru — APPROVED** [review]
Not seeing any regression and Easy Effects shows audio with aplay and Davinici

**Pull request merged**
