### PR TITLE
fix: Discord notification sounds

### PR DESCRIPTION
**Pull request by mmstick**
Found from https://wiki.archlinux.org/title/PipeWire#No_notification_sounds_from_Discord

Was able to replicate and this did fix it for me.

### CODE REVIEW

**Review by n3m0-22 — APPROVED** [review]
Reproduced the issue. This fixes it. I see no regressions.

**Comment by mmstick** [comment]
It may be useful to go through other common communication platforms and see if they need any tweaks.

**Comment by n3m0-22** [comment]
I'll check.

**Review by jackpot51 — APPROVED** [review]

**Comment by n3m0-22** [comment]
Sound on Slack and Mattermost is working fine for me.

**Pull request merged**
