### PR TITLE
Pipewire 1.2.0

### LINKED ISSUE #74: 1.2.6 Rebase
bump pipewire to [1.2.6](https://gitlab.freedesktop.org/pipewire/pipewire/-/tags/1.2.6)

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by rexendevar** [comment]
Experiencing pretty severe bugs with this. Running `pw-metadata -n settings 0 clock.force-quantum 128; pw-metadata -n settings 0 clock.force-rate 48000` (which is a fairly standard command imo) almost always messes up every program connected to the audio system. Running it from within a program (in my case Reaper) has the potential to create a segmentation fault, but most of the time will simply not connect the audio back up properly. See Reaper crash log: https://mega.nz/file/VqUBmQyA#HPA18p_Ugx5c3RgpmNZ-RurLkgGSlYVXt3fM4K-LtBA

**Review by jacobgkau — CHANGES_REQUESTED** [review]
With this update installed, the pang12's speakers don't work on boot. (The volume change click, the Settings test sounds, and Firefox video playback all don't output any sound.)

If I plug in a headset, then the *speakers* start working (outputting sound at the same time as the headset), and they continue working if I unplug the headset. I can recreate the issue again by powering off & back on.

(This issue does not occur on oryp8, so it's hardware-specific to some extent.)

**Comment by ianhundere** [comment]
> Experiencing pretty severe bugs with this. Running `pw-metadata -n settings 0 clock.force-quantum 128; pw-metadata -n settings 0 clock.force-rate 48000` (which is a fairly standard command imo) almost always messes up every program connected to the audio system. Running it from within a program (in my case Reaper) has the potential to create a segmentation fault, but most of the time will simply not connect the audio back up properly. See Reaper crash log: https://mega.nz/file/VqUBmQyA#HPA18p_Ugx5c3RgpmNZ-RurLkgGSlYVXt3fM4K-LtBA

@rexendevar maybe try adjusting `api.alsa.period-size` as per https://github.com/robbert-vdh/dotfiles/blob/5eb1983235c130f291ba6d0749cb71a90f580140/modules/pipewire/wireplumber/main.lua.d/90-alsa-config.lua#L16 to see if that helps? 

edit: [1.2.1](https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/1.2.1) has also been released which resolves some bugs/regressions. 

edit2: @mmstick @jacobgkau what's the expectation for when this will be merged?

**Comment by mmstick** [comment]
Can't merge if there are regressions. We'll try the next pipewire release.

**Comment by ianhundere** [comment]
@mmstick @jacobgkau [1.2.1 ](https://gitlab.freedesktop.org/pipewire/pipewire/-/tags/1.2.1)has been released.

**Comment by rexendevar** [comment]
> @mmstick @jacobgkau [1.2.1 ](https://gitlab.freedesktop.org/pipewire/pipewire/-/tags/1.2.1)has been released.

I'm going to attempt to install 1.2.1. Are the build options any different from the default?

**Comment by rexendevar** [comment]
Well, I've compiled Pipewire 1.2.1 and I'm having the same issues.

**Pull request closed without merging**
