### PR TITLE
Pipewire 0.3.64

### PR DESCRIPTION
**Pull request by mmstick**
https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.64

### CODE REVIEW

**Review by 13r0ck — APPROVED** [review]

**Review by n3m0-22 — APPROVED** [review]
All testing passed. Looks good to me. I also confirmed #32 is still resolved with this update. 

[pipewire-0.3.64-testing.txt](https://github.com/pop-os/pipewire/files/10476218/pipewire-0.3.64-testing.txt)

**Comment by jackpot51** [comment]
@13r0ck can you force push this?

**Comment by 13r0ck** [comment]
Sure can

**Comment by jackpot51** [comment]
Oops, meant to say @mmstick since he made the PR. Anyways, its all set now!

**Comment by le-patenteux** [comment]
Hello fine folks, I answered in the closed issue #32 but I wanted to make sure it reached you.

I am sorry for the delay, Github won't send me notifications when someone answers an Issue, and I don't use Github a lot

The important part is that the issue is still present for me and my colleagues to this day. I am on Pipewire 0.3.66

The audio interface I am using has the following entry on lsusb:
`ID 1397:0508 BEHRINGER International GmbH UMC204HD 192k`

Have a nice day, and thank you for the amazing work you are doing!

**Pull request closed without merging**
