### PR TITLE
Pipewire 0.3.67 rebase

### PR DESCRIPTION
**Pull request by mmstick**
This bugfix release should improve audio stability for bluetooth audio connections.

https://www.phoronix.com/news/PipeWire-0.3.67-Released
https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.67

### CODE REVIEW

**Review by n3m0-22 — COMMENTED** [review]
Everything but Audacity is working.

PipeWire rebase regression testing:

- [x] Built-in speakers and microphone still work, volume adjustment still plays sound.
- [x] GNOME Sound Recorder still records and plays back.
- [ ] Audacity records and plays back.
    - [ ] JACK mode
    - [ ] ALSA mode
- [x] DaVinci Resolve audio still works as expected (without lag) & shows up in pavucontrol.
    - Volume adjustment sounds stop working when Resolve is open, not a regression.
- [x] Ardour works in JACK mode Bitwig works in native PIpeWire mode.
- [x] Output via GPU (e.g. HDMI and DisplayPort audio) works.
- [x] Headphone/microphone and combo headset both work.
- [x] Built-in GNOME Shell screen recording still works.
- [x] Still able to share screen, webcam, and microphone via Jitsi in Firefox.
- [x] Bluetooth microphone input works with no stuttering.

[audacity-log.txt](https://github.com/pop-os/pipewire/files/10983221/audacity.txt)

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
I have tested both the deb and flatpak of Audacity and have been able to get ALSA mode working sometimes, but never JACK mode. Also when switching back from JACK mode to ALSA mode if it was working before it stops working.

**Review by 13r0ck — APPROVED** [review]

**Comment by mmstick** [comment]
We should wait for some patches to the issue then. I could rebase on the latest commit so we can see if there's a fix in there.

**Comment by hojjatabdollahi** [comment]
I'm so happy. I finally can use my Bose headphone with my laptop without any gaps or lags or glitches. The commits from today did it, not the ones from yesterday.
Thank you.

**Review by n3m0-22 — APPROVED** [review]
Audacity is now working JACK and ALSA both the deb and flatpak. I have gone over the whole checklist again, and have seen no regressions. Looks good to me.

[pipewire-0.3.67-testing.txt](https://github.com/pop-os/pipewire/files/10994575/pipewire-0.3.67-testing.txt)

**Pull request merged**
