### PR TITLE
Pipewire 1.2.0

### LINKED ISSUE #74: 1.2.6 Rebase
bump pipewire to [1.2.6](https://gitlab.freedesktop.org/pipewire/pipewire/-/tags/1.2.6)

### PR DESCRIPTION
**Pull request by mmstick**
Closes #74

### CODE REVIEW

**Comment by jacobgkau** [comment]
I'm ignoring the failing i386 Noble build because this is merging into `master_jammy`.

**Comment by mmstick** [comment]
Seems it fails due to being out of memory on i386 when compressing with zstd

**Comment by jacobgkau** [comment]
Why was this merged without approvals?

**Comment by mmstick** [comment]
Reverted

**Pull request merged**
