### PR TITLE
Allow use of a input port if no outputs are available

### PR DESCRIPTION
**Pull request by jackpot51**
Based on #46

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

**Comment by XV-02** [comment]
Not seeing any promise at first blush. Given that Josh has been investigating, I'll touch base with him first thing tomorrow and start from clean. Should have an update by EOD tomorrow.

**Comment by jackpot51** [comment]
> Not seeing any promise at first blush. Given that Josh has been investigating, I'll touch base with him first thing tomorrow and start from clean. Should have an update by EOD tomorrow.

What this specifically fixes is not having an input device selected when there is no line out plugged in, for thelio-b5. It does not fix all audio behavior.

**Comment by XV-02** [comment]
Okay, so, the behaviours around B5 have been sufficiently complex that I need to get a handle on this if I am to test it with confidence. As I understand it so far:

1) This started with the update to `alsa-ucm-conf` (from `1.2.6.3` to `1.2.8`). At that point, the previously working `line-in` port, as routinely tested by the assembly team as part of the shipping process, ceased function.

2) Since then, a number of different behaviours have been witnessed as various fixes have been attempted. Most recently are two major patterns: 
    A) neither `line-in` nor `mic-in` function without `line-out` being populated. 
    B) functionality of the various ports can be influenced by populating different ports during the installation of certain packages (I believe `alsa-ucm-conf`)
    
~~3) The objective of this PR is to allow the `line-in` and `mic-in` ports to work without the `line-out` port being populated.~~

Is this correct?

As to this issue, then this isn't achieving its objective as far as I can see. My next step is to wipe the system and start entirely clean. But, when I added this change, I still needed `line-out` populated in order to use `mic-in`, and had no success with `line-in`

**Comment by XV-02** [comment]
From a clean install off of the latest released iso, with none of the ports populated until _after_ fully updating (including this PR):

I'm seeing nothing on `line-in`
I am only seeing `mic-in` work when `line-out` is populated
`line-out` is fine.

**Comment by jackpot51** [comment]
This change specifically fixes the times when the line out jack is unplugged and the system switches to an empty input device even when an input device is plugged in. It does not fix the mic in or line in not working under some circumstances.

**Comment by XV-02** [comment]
Before this:
1) `line-out` is populated
2) `mic-in` is plugged into
3) `mic-in` works
4) `line-out` is unplugged
5) `mic-in` **stops working**; gnome-control-center continues to report the `mic-in` port as an input source.

After this:
1) `line-out` is populated
2) `mic-in` is plugged into
3) `mic-in` works
4) `line-out` is unplugged
5) `mic-in` **continues working**; gnome-control-center continues to report the `mic-in` port as an input source.

In the context of:

> This change specifically fixes the times when the line out jack is unplugged and the system switches to an empty input device even when an input device is plugged in. It does not fix the mic in or line in not working under some circumstances.

That sounds like the desired behaviour. Is that correct?

**Comment by jackpot51** [comment]
> Before this:
> 
>     1. `line-out` is populated
> 
>     2. `mic-in` is plugged into
> 
>     3. `mic-in` works
> 
>     4. `line-out` is unplugged
> 
>     5. `mic-in` **stops working**; gnome-control-center continues to report the `mic-in` port as an input source.
> 
> 
> After this:
> 
>     1. `line-out` is populated
> 
>     2. `mic-in` is plugged into
> 
>     3. `mic-in` works
> 
>     4. `line-out` is unplugged
> 
>     5. `mic-in` **continues working**; gnome-control-center continues to report the `mic-in` port as an input source.
> 
> 
> In the context of:
> 
> > This change specifically fixes the times when the line out jack is unplugged and the system switches to an empty input device even when an input device is plugged in. It does not fix the mic in or line in not working under some circumstances.
> 
> That sounds like the desired behaviour. Is that correct?

Correct

**Review by XV-02 — APPROVED** [review]

**Pull request merged**
