### PR TITLE
0.3.56 Rebase

### LINKED ISSUE #16: [Allen & Heath Qu-Pac] regression since 0.3.53+ / no audio inputs unless manual selection of config profile ("Pro") in pulse audio control
since updating to 0.3.53 audio is no longer inputted to my daw, bitwig 4.3.1.

i confirmed this was the issue by using timeshift to revert before the update, running bitwig to confirm audio was being inputted and then updated to 0.3.53.

maybe we can rebase to 0.3.54 to see if that fixes it?

https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/NEWS

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by 13r0ck — APPROVED** [review]

**Comment by jacobgkau** [comment]
This morning, I'm running into the issue I mentioned in the [last rebase](https://github.com/pop-os/pipewire/pull/17#pullrequestreview-1037798054) where the Audacity .deb is not seeing a JACK server available when running 0.3.56 on oryp8 (no issue when I downgrade to 0.3.55.) It's also affecting the Ardour .deb (Flatpak versions of either app work fine with JACK.) Unlike last time, uninstalling and reinstalling the staging branch has not fixed the issue yet. I've got the same version of PipeWire on lemp10, and it's not having the issue with deb installs of those apps.

Audacity includes this terminal output when it fails to detect JACK on oryp8:

```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
```

Ardour output includes four copies of those errors instead of two. Having `pipewire-audio-client-libraries` installed or uninstalled doesn't make a difference.

**Comment by jacobgkau** [comment]
On the oryp8, starting with `pw-jack` as used to be necessary gets JACK working for the .deb programs.

https://github.com/pop-os/pipewire/pull/1 mentioned installing pipewire-jack config to `/etc/ld.so.conf.d/`, which I think is what made `pw-jack` no longer necessary. On oryp8, I have nothing in that directory with the new or old packages; on lemp10, I have three files in that config, but none of them are PipeWire-related. Still unsure why the issue is only occurring on one of the two test machines and why it doesn't happen on the older version.

**Comment by jacobgkau** [comment]
Ok, oryp8 is now failing to see JACK even on 0.3.55, so this is no longer a regression, at least.

Running `sudo ldconfig` on the lemp10 broke it there, too; that explains the difference in behavior, it seems to me like this got broken but wasn't caught during regression testing because `sudo ldconfig` wasn't run while testing (and it would also remain working on any real-world systems until the next time `sudo ldconfig` is run.)

Seems like this should be straightforward to fix by putting the config file back in `/etc/ld.so.conf.d/`, I'm currently trying to confirm exactly where it should be pointing to.

**Comment by jacobgkau** [comment]
Looks like creating `/etc/ld.so.conf.d/pipewire-jack-x86_64.conf` with the contents `/usr/lib/x86_64-linux-gnu/pipewire-0.3/jack` and then running `sudo ldconfig` again fixes this issue. We'll want to install that file.

**Review by jacobgkau — APPROVED** [review]
a3894c2 fixed JACK on both machines, without having to change any files or run `sudo ldconfig` manually.

Regression testing passed:

- [X] Built-in speakers and microphone still work, volume adjustment still plays sound.
- [X] GNOME Sound Recorder still records and plays back.
- [X] Audacity records and plays back.
    - [X] JACK mode
    - [X] ALSA mode
- [X] DaVinci Resolve audio still works as expected (without lag) & shows up in pavucontrol.
    - Volume adjustment sounds stop working when Resolve is open, not a regression.
- [X] Ardour works in JACK mode, Bitwig works in native PIpeWire mode.
- [X] Output via GPU (e.g. HDMI and DisplayPort audio) works.
- [X] Headphone/microphone and combo headset both work.
- [X] Built-in GNOME Shell screen recording still works.
- [X] Still able to share screen, webcam, and microphone via Jitsi in Firefox.
- [X] Bluetooth microphone input works with no stuttering.
    - Checked by @bflanagin and @n3m0-22.

**Pull request merged**
