### PR TITLE
Pipewire 0.3.77

### LINKED ISSUE #56: 0.3.77 Rebase
bump pipewire to [0.3.77](https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.77)

### PR DESCRIPTION
**Pull request by mmstick**
Closes #56

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
This is working fine so far, but we need to fix the i386 build for it to not have issues installing on systems with 32-bit libraries (e.g. Steam).

**Comment by mmstick** [comment]
I've not successfully figured out how to get systemd to install on i386 with our sbuild CI script. May need a tweak to our systemd packaging. It seems to demand to install chrony even though systemd-timesyncd should satisfy the time-daemon dependency.

**Comment by jacobgkau** [comment]
> systemd-timesyncd should satisfy the time-daemon dependency.

When we moved the Chrony dependency from pop-desktop to systemd (to fix time sync on Ubuntu installations after we made our systemd-timesyncd package do nothing), I think we went with a hard dependency on Chrony only for systemd due to an apt bug with or-dependencies at the time, looking back at https://github.com/pop-os/systemd/pull/33.

I am confused why this would be an issue now but not for https://github.com/pop-os/pipewire/pull/55 last month when the Chrony change was back in April.

**Comment by mmstick** [comment]
It's been a little over a month since our last pipewire update. I think this is the only package that has systemd as a dependency.

**Comment by mmstick** [comment]
I'll make a PR so that chrony's not required for i386.

**Comment by jacobgkau** [comment]
We're depending on Ubuntu's Chrony build, which [doesn't have](https://packages.ubuntu.com/jammy/chrony) an i386 build, but what's confusing is that if Chrony missing for i386 was the issue, then Ubuntu would have had to drop the i386 build of it within the last month since https://github.com/pop-os/pipewire/pull/55. Otherwise, something else changed to break this.

**Comment by mmstick** [comment]
It's probably fine for Ubuntu because `<time-daemon>` is also provided by systemd-timesyncd and ntp.

**Comment by mmstick** [comment]
On second thought, it might be easier to just build chrony for i386.

**Comment by mmstick** [comment]
The systemd change worked. i386 is built now.

**Comment by jacobgkau** [comment]
Regression testing passed:

- [X] Built-in speakers and microphone still work, volume adjustment still plays sound.
- [X] GNOME Sound Recorder still records and plays back.
- [X] Audacity records and plays back.
    - [X] JACK mode
    - [X] ALSA mode
- [X] DaVinci Resolve audio still works as expected (without lag) & shows up in pavucontrol.
    - Volume adjustment sounds stop working when Resolve is open, not a regression.
- [X] Ardour works in JACK mode, Bitwig works in native PipeWire mode.
- [X] Output via GPU (e.g. HDMI and DisplayPort audio) works.
    - [X] Intel GPU system
    - [X] NVIDIA GPU system
- [X] Headphone/microphone and combo headset both work.
- [X] Built-in GNOME Shell screen recording still works.
    - Option to show cursor is broken, stuck in top-left in recording (not a regression).
    - Only starts recording once per GNOME Shell restart (not a regression).
- [X] Still able to share screen, webcam, and microphone via Jitsi in Firefox.
- [X] Bluetooth microphone input works with no stuttering.

**Review by jacobgkau — APPROVED** [review]

**Pull request merged**
