### PR TITLE
0.3.55 Rebase

### PR DESCRIPTION
**Pull request by mmstick**
New version, rebased onto Debian repository, then rebased on upstream 0.3.55 release.

### CODE REVIEW

**Comment by jacobgkau** [comment]
This will not install. It looks like `pipewire-audio-client-libraries` is being replaced by new packages called `pipewire-alsa` and `pipewire-jack`, but `pop-desktop` still depends on `pipewire-audio-client-libraries`. We may need an accompanying PR to https://github.com/pop-os/desktop to change the dependency.

**Review by 13r0ck — APPROVED** [review]

**Comment by jacobgkau** [comment]
With the transitional package added, it's getting a little further, but most of the packages are still being held back:

```
system76@pop-os:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  gstreamer1.0-pipewire libpipewire-0.3-0 libpipewire-0.3-modules libspa-0.2-bluetooth libspa-0.2-jack libspa-0.2-modules pipewire
  pipewire-audio-client-libraries pipewire-bin pipewire-pulse pop-desktop
The following packages will be upgraded:
  libpipewire-0.3-common
1 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
```

Installing the one available upgrade does not get the rest of the packages to install, they're still held back after that and the Pop!_Shop still crashes.

**Comment by mmstick** [comment]
Rebased on 0.3.55. Transitional packaging was also fixed.

**Comment by n3m0-22** [comment]
Seems to be working now. The packages are no longer being held back and are installing with `sudo apt upgrade`. After running `pipewire-alsa` and ` pipewire-jack` are present and `pipewire-audio-client-libraries` is removed.

**Review by jacobgkau — CHANGES_REQUESTED** [review]
This is currently causing DaVinci Resolve to have delayed audio playback, a regression over the current release.

It looks like neither the `/etc/alsa/conf.d/99-pipewire-default.conf` symlink or the `/usr/share/alsa/alsa.conf.d/99-pipewire-default.conf` file is present in the new packaging, currently.

**Comment by jacobgkau** [comment]
Comparing [this line](https://github.com/pop-os/pipewire/blob/57b1a25d13567584d29b99e9b008492de63dbd05/debian/pipewire-alsa.install#L4) in the new `pipewire-alsa.install` file and [this line](https://github.com/pop-os/pipewire/blob/21b09675291d1f75d13d691534572f8d82b1c908/debian/pipewire-audio-client-libraries.install#L7) in the old `pipewire-audio-client-libraries.install` file, I think we may just need to remove the second portion of the new file's line so it doesn't get installed as an example?

**Comment by mmstick** [comment]
Yeah that sounds right

**Comment by jacobgkau** [comment]
`/usr/share/alsa/alsa.conf.d/99-pipewire-default.conf` is present now, but the symlink to it at `/etc/alsa/conf.d/99-pipewire-default.conf` is still missing, and the delay is still happening.

**Comment by jacobgkau** [comment]
Probably needs to be added to [pipewire-alsa.links](https://github.com/pop-os/pipewire/blob/1656cb9150c101154a304d63b180a92921863eff/debian/pipewire-alsa.links) to match what used to be in [pipewire-audio-client-libraries.links](https://github.com/pop-os/pipewire/blob/21b09675291d1f75d13d691534572f8d82b1c908/debian/pipewire-audio-client-libraries.links#L2).

**Comment by jacobgkau** [comment]
The Resolve delay issue is fixed now.

**Comment by jacobgkau** [comment]
I'm getting a segmentation fault trying to start Ardour for some reason. It doesn't happen with current PipeWire (using JACK mode). Still trying to figure out why.

**Comment by jacobgkau** [comment]
The Ardour crash can be recreated after removing `~/.config/ardour6` and starting it with a default configuration. The crash only occurs in JACK mode, not ALSA mode or Pulseaudio mode. The buffer size selected for JACK does not seem to matter. The issue only seems to affect the .deb version of Ardour (from the Ubuntu jammy repository), not the Flatpak version.

**Comment by mmstick** [comment]
Found this commit recently pushed to pipewire

https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/40552a0e914c3aef48ce59ce1bfb9d80516aa893

Seems like a simple cherry pick for this release.

**Comment by jacobgkau** [comment]
100cfa9 has fixed the Ardour crash.

**Review by jacobgkau — APPROVED** [review]
Had a brief instance this morning of the Audacity .deb not detecting JACK as an option (the Flatpak was not affected), but haven't been able to recreate since downgrading & re-upgrading PipeWire. (Checked it doesn't happen anymore regardless of whether `pipewire-audio-client-libraries` is still present or has been autoremoved; also tried from a cold boot like how it originally occurred, still not happening.)

Testing is passing:

- [X] Built-in speakers and microphone still work, volume adjustment still plays sound.
- [X] GNOME Sound Recorder still records and plays back.
- [X] Audacity records and plays back.
    - [X] JACK mode
    - [X] ALSA mode
- [X] DaVinci Resolve audio still works as expected (without lag) & shows up in pavucontrol.
    - Volume adjustment sounds stop working when Resolve is open, not a regression.
- [X] Ardour works in JACK mode, Bitwig works in native PIpeWire mode.
- [X] Output via GPU (e.g. HDMI and DisplayPort audio) works.
- [X] Headphone/microphone and combo headset both work.
- [X] Built-in GNOME screen recording still works, still able to share screen in Firefox.
- [X] Bluetooth microphone input works with no stuttering.

**Pull request merged**
